# Generated by Django 4.2 on 2023-04-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1, help_text='The day of the week for this time slot'),
        ),
    ]
