# Generated by Django 4.2 on 2023-04-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobschedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobschedule',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
    ]
