# Generated by Django 4.2.4 on 2023-09-02 03:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faqentry_created_on_faqentry_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='body',
            field=tinymce.models.HTMLField(help_text='The response to this question'),
        ),
    ]
