# Generated by Django 4.2 on 2023-04-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_customuser_biography_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
