# Generated by Django 4.2.5 on 2023-09-04 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_customuser_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_url',
        ),
        migrations.CreateModel(
            name='CustomUserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
